In [ ]:
#Pandas is a Python library
#Pandas is used to analyze data
#What is Pandas?
#Pandas is a Python library used for working with data sets.
#It has function for analyzing,cleaning,exploring and manipulating data
#To analyze big data and make conclusions based on statistical theories
#Relevant data is very important in datascience
#pip install pandas

In [ ]:
#Pandas Series
#What is a Series?
#A pandas series is like a column in a table
#It is one dimensional array holding data of any type

In [1]:
import pandas as pd
a=[1,7,10]
my1=pd.Series(a)
print(my1)

0     1
1     7
2    10
dtype: int64

In [2]:
print(my1[0])

1

In [3]:
my1=pd.Series(a,index=["x","y","z"])
print(my1)

x     1
y     7
z    10
dtype: int64

In [6]:
print(my1["x"])

1

In [10]:
my2={101:"azar",102:"mohamed",103:"sai"}
result=pd.Series(my2,index=[101,102])
print(result)

101       azar
102    mohamed
dtype: object

In [ ]:
#DataFrames
#Data sets in pandas are usually multi-dimensional tables called dataFrames
#Series is like a column,a dataframe is the whole table

In [11]:
data={"c1":[100,200,300],"c2":[400,500,600]}
my1=pd.DataFrame(data)
print(my1)

    c1   c2
0  100  400
1  200  500
2  300  600

In [ ]:
#Locate Row
#Pandas use the loc attribute to return one or more specified rows

In [14]:
print(my1.loc[0])

c1    100
c2    400
Name: 0, dtype: int64

In [15]:
#Use a list of indexes
print(my1.loc[[0,1]])

    c1   c2
0  100  400
1  200  500

In [ ]:
#Named indexes
#With the index argument you can name your own indexes

In [16]:
my1

    c1   c2
0  100  400
1  200  500
2  300  600

In [20]:
my2=pd.DataFrame(data,index=["d1","d2","d3"])
print(my2)

     c1   c2
d1  100  400
d2  200  500
d3  300  600

In [21]:
#Locate Named Indexes
#Refer to the named index
print(my2.loc["d1"])

c1    100
c2    400
Name: d1, dtype: int64

In [ ]:
#Load files into a dataFrame

In [22]:
df=pd.read_csv('Datasets/Position_Salaries.csv')
df

            Position  Level   Salary
0   Business Analyst      1    45000
1  Junior Consultant      2    50000
2  Senior Consultant      3    60000
3            Manager      4    80000
4    Country Manager      5   110000
5   Regional Manager      6   150000
6            Partner      7   200000
7     Senior Partner      8   300000
8            C-level      9   500000
9                CEO     10  1000000

In [23]:
print(pd.options.display.max_rows)

60

In [24]:
print(pd.options.display.max_columns)

20

In [21]:
import numpy as np
import pandas as pd
data={'One':pd.Series([1,2,3,4],index=['a','b','c','d']),
      'two':pd.Series([1,2,3,4],index=['a','b','c','d'])}
table=pd.DataFrame(data)
table

   One  two
a    1    1
b    2    2
c    3    3
d    4    4

In [5]:
#DataFrame-Add and delete the column
data={'One':pd.Series([1,2,3,4],index=['a','b','c','d']),
      'two':pd.Series([1,2,3,4],index=['a','b','c','d'])}
table=pd.DataFrame(data)
table['three']=pd.Series([10,20,30,40],index=['a','b','c','d'])
print(table)

   One  two  three
a    1    1     10
b    2    2     20
c    3    3     30
d    4    4     40

In [3]:
del table['One']
print(table)

   two  three
a    1     10
b    2     20
c    3     30
d    4     40

In [4]:
table.pop('two')
print(table)

   three
a     10
b     20
c     30
d     40

In [6]:
table

   One  two  three
a    1    1     10
b    2    2     20
c    3    3     30
d    4    4     40

In [ ]:
#DataFrame-Add and delete of Rows

In [15]:
print(table.loc['a'])
print(table)

One       1
two       1
three    10
Name: a, dtype: int64
   One  two  three
a    1    1     10
b    2    2     20
c    3    3     30
d    4    4     40

In [11]:
print(table)

   One  two  three
a    1    1     10
b    2    2     20
c    3    3     30
d    4    4     40

In [17]:
print(table)

   One  two  three
a    1    1     10
b    2    2     20
c    3    3     30
d    4    4     40

In [18]:
row=pd.DataFrame([[11,12,13],[14,15,16]],columns=['One','two','three'])
table=table.append(row)
table

C:\Users\azart\AppData\Local\Temp\ipykernel_9288\998529836.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  table=table.append(row)

   One  two  three
a    1    1     10
b    2    2     20
c    3    3     30
d    4    4     40
0   11   12     13
1   14   15     16

In [19]:
table=table.drop('a')

In [20]:
table

   One  two  three
b    2    2     20
c    3    3     30
d    4    4     40
0   11   12     13
1   14   15     16

In [24]:
df_test=pd.DataFrame(np.random.rand(5,5),['A','B','C','D','E'],['W','X','Y','Z','A'])
df_test

          W         X         Y         Z         A
A  0.063321  0.358409  0.780382  0.506309  0.141190
B  0.786915  0.636103  0.477976  0.909348  0.803689
C  0.729654  0.060101  0.031305  0.032103  0.039962
D  0.624345  0.094059  0.099552  0.281598  0.466293
E  0.722301  0.116752  0.149587  0.564291  0.065103

In [25]:
print(df_test[['W','A']])

          W         A
A  0.063321  0.141190
B  0.786915  0.803689
C  0.729654  0.039962
D  0.624345  0.466293
E  0.722301  0.065103

In [26]:
print(df_test.loc['A'])

W    0.063321
X    0.358409
Y    0.780382
Z    0.506309
A    0.141190
Name: A, dtype: float64

In [27]:
print(df_test.loc[['A'],['W']])

          W
A  0.063321

In [28]:
print(df_test.loc[['A','B'],['W','X']])

          W         X
A  0.063321  0.358409
B  0.786915  0.636103

In [29]:
df_test['NEWCOL']=df_test['W']+df_test['X']
print(df_test)

          W         X         Y         Z         A    NEWCOL
A  0.063321  0.358409  0.780382  0.506309  0.141190  0.421730
B  0.786915  0.636103  0.477976  0.909348  0.803689  1.423018
C  0.729654  0.060101  0.031305  0.032103  0.039962  0.789754
D  0.624345  0.094059  0.099552  0.281598  0.466293  0.718404
E  0.722301  0.116752  0.149587  0.564291  0.065103  0.839053

In [31]:
df_test.shape

(5, 6)

In [38]:
print(df_test[(df_test['NEWCOL']>1)])

          W         X         Y         Z         A    NEWCOL
B  0.786915  0.636103  0.477976  0.909348  0.803689  1.423018

In [36]:
print(df_test[(df_test['W']<0.4)&(df_test['Y']>0.3)])

          W         X         Y         Z        A   NEWCOL
A  0.063321  0.358409  0.780382  0.506309  0.14119  0.42173

In [39]:
df_test

          W         X         Y         Z         A    NEWCOL
A  0.063321  0.358409  0.780382  0.506309  0.141190  0.421730
B  0.786915  0.636103  0.477976  0.909348  0.803689  1.423018
C  0.729654  0.060101  0.031305  0.032103  0.039962  0.789754
D  0.624345  0.094059  0.099552  0.281598  0.466293  0.718404
E  0.722301  0.116752  0.149587  0.564291  0.065103  0.839053