In [1]:
#Pandas is a Python library
#Pandas is used to analyze data
#What is Pandas?
#Pandas is a Python library used for working with data sets.
#It has function for analyzing,cleaning,exploring and manipulating data
#To analyze big data and make conclusions based on statistical theories
#Relevant data is very important in datascience
#pip install pandas

In [2]:
#Pandas Series
#What is a Series?
#A pandas series is like a column in a table
#It is one dimensional array holding data of any type

In [3]:
import pandas as pd
a=[1,7,10]
my1=pd.Series(a)
print(my1)

0     1
1     7
2    10
dtype: int64

In [4]:
print(my1[0])

1

In [5]:
my1=pd.Series(a,index=["x","y","z"])
print(my1)

x     1
y     7
z    10
dtype: int64

In [6]:
print(my1["x"])

1

In [7]:
my2={101:"azar",102:"mohamed",103:"sai"}
result=pd.Series(my2,index=[101,102])
print(result)

101       azar
102    mohamed
dtype: object

In [8]:
#DataFrames
#Data sets in pandas are usually multi-dimensional tables called dataFrames
#Series is like a column,a dataframe is the whole table

In [9]:
data={"c1":[100,200,300],"c2":[400,500,600]}
my1=pd.DataFrame(data)
print(my1)

    c1   c2
0  100  400
1  200  500
2  300  600

In [10]:
#Locate Row
#Pandas use the loc attribute to return one or more specified rows

In [11]:
print(my1.loc[0])

c1    100
c2    400
Name: 0, dtype: int64

In [12]:
#Use a list of indexes
print(my1.loc[[0,1]])

    c1   c2
0  100  400
1  200  500

In [13]:
#Named indexes
#With the index argument you can name your own indexes

In [14]:
my1

    c1   c2
0  100  400
1  200  500
2  300  600

In [15]:
my2=pd.DataFrame(data,index=["d1","d2","d3"])
print(my2)

     c1   c2
d1  100  400
d2  200  500
d3  300  600

In [16]:
#Locate Named Indexes
#Refer to the named index
print(my2.loc["d1"])

c1    100
c2    400
Name: d1, dtype: int64

In [17]:
#Load files into a dataFrame

In [18]:
df=pd.read_csv('Datasets/Position_Salaries.csv')
df

            Position  Level   Salary
0   Business Analyst      1    45000
1  Junior Consultant      2    50000
2  Senior Consultant      3    60000
3            Manager      4    80000
4    Country Manager      5   110000
5   Regional Manager      6   150000
6            Partner      7   200000
7     Senior Partner      8   300000
8            C-level      9   500000
9                CEO     10  1000000

In [19]:
print(pd.options.display.max_rows)

60

In [20]:
print(pd.options.display.max_columns)

20

In [21]:
import numpy as np
import pandas as pd
data={'One':pd.Series([1,2,3,4],index=['a','b','c','d']),
      'two':pd.Series([1,2,3,4],index=['a','b','c','d'])}
table=pd.DataFrame(data)
table

   One  two
a    1    1
b    2    2
c    3    3
d    4    4

In [22]:
#DataFrame-Add and delete the column
data={'One':pd.Series([1,2,3,4],index=['a','b','c','d']),
      'two':pd.Series([1,2,3,4],index=['a','b','c','d'])}
table=pd.DataFrame(data)
table['three']=pd.Series([10,20,30,40],index=['a','b','c','d'])
print(table)

   One  two  three
a    1    1     10
b    2    2     20
c    3    3     30
d    4    4     40

In [23]:
del table['One']
print(table)

   two  three
a    1     10
b    2     20
c    3     30
d    4     40

In [24]:
table.pop('two')
print(table)

   three
a     10
b     20
c     30
d     40

In [25]:
table

   three
a     10
b     20
c     30
d     40

In [26]:
#DataFrame-Add and delete of Rows

In [27]:
print(table.loc['a'])
print(table)

three    10
Name: a, dtype: int64
   three
a     10
b     20
c     30
d     40

In [28]:
print(table)

   three
a     10
b     20
c     30
d     40

In [29]:
print(table)

   three
a     10
b     20
c     30
d     40

In [30]:
row=pd.DataFrame([[11,12,13],[14,15,16]],columns=['One','two','three'])
table=table.append(row)
table

C:\Users\azart\AppData\Local\Temp\ipykernel_27988\998529836.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  table=table.append(row)

   three   One   two
a     10   NaN   NaN
b     20   NaN   NaN
c     30   NaN   NaN
d     40   NaN   NaN
0     13  11.0  12.0
1     16  14.0  15.0

In [31]:
table=table.drop('a')

In [32]:
table

   three   One   two
b     20   NaN   NaN
c     30   NaN   NaN
d     40   NaN   NaN
0     13  11.0  12.0
1     16  14.0  15.0

In [33]:
df_test=pd.DataFrame(np.random.rand(5,5),['A','B','C','D','E'],['W','X','Y','Z','A'])
df_test

          W         X         Y         Z         A
A  0.117022  0.419714  0.341500  0.631714  0.077726
B  0.747004  0.962553  0.139678  0.727101  0.841971
C  0.660239  0.883132  0.982043  0.226082  0.561321
D  0.601463  0.080718  0.999288  0.407770  0.125858
E  0.769375  0.178236  0.528002  0.617595  0.590948

In [34]:
print(df_test[['W','A']])

          W         A
A  0.117022  0.077726
B  0.747004  0.841971
C  0.660239  0.561321
D  0.601463  0.125858
E  0.769375  0.590948

In [35]:
print(df_test.loc['A'])

W    0.117022
X    0.419714
Y    0.341500
Z    0.631714
A    0.077726
Name: A, dtype: float64

In [36]:
print(df_test.loc[['A'],['W']])

          W
A  0.117022

In [37]:
print(df_test.loc[['A','B'],['W','X']])

          W         X
A  0.117022  0.419714
B  0.747004  0.962553

In [38]:
df_test['NEWCOL']=df_test['W']+df_test['X']
print(df_test)

          W         X         Y         Z         A    NEWCOL
A  0.117022  0.419714  0.341500  0.631714  0.077726  0.536736
B  0.747004  0.962553  0.139678  0.727101  0.841971  1.709557
C  0.660239  0.883132  0.982043  0.226082  0.561321  1.543371
D  0.601463  0.080718  0.999288  0.407770  0.125858  0.682181
E  0.769375  0.178236  0.528002  0.617595  0.590948  0.947612

In [39]:
df_test.shape

(5, 6)

In [40]:
print(df_test[(df_test['NEWCOL']>1)])

          W         X         Y         Z         A    NEWCOL
B  0.747004  0.962553  0.139678  0.727101  0.841971  1.709557
C  0.660239  0.883132  0.982043  0.226082  0.561321  1.543371

In [41]:
print(df_test[(df_test['W']<0.4)&(df_test['Y']>0.3)])

          W         X       Y         Z         A    NEWCOL
A  0.117022  0.419714  0.3415  0.631714  0.077726  0.536736

In [42]:
df_test

          W         X         Y         Z         A    NEWCOL
A  0.117022  0.419714  0.341500  0.631714  0.077726  0.536736
B  0.747004  0.962553  0.139678  0.727101  0.841971  1.709557
C  0.660239  0.883132  0.982043  0.226082  0.561321  1.543371
D  0.601463  0.080718  0.999288  0.407770  0.125858  0.682181
E  0.769375  0.178236  0.528002  0.617595  0.590948  0.947612

In [43]:
df_test.to_excel('test1.xlsx',sheet_name="mysheet")
print(df_test)

          W         X         Y         Z         A    NEWCOL
A  0.117022  0.419714  0.341500  0.631714  0.077726  0.536736
B  0.747004  0.962553  0.139678  0.727101  0.841971  1.709557
C  0.660239  0.883132  0.982043  0.226082  0.561321  1.543371
D  0.601463  0.080718  0.999288  0.407770  0.125858  0.682181
E  0.769375  0.178236  0.528002  0.617595  0.590948  0.947612

In [44]:
df_test.to_csv('test2.csv')
print(df_test)

          W         X         Y         Z         A    NEWCOL
A  0.117022  0.419714  0.341500  0.631714  0.077726  0.536736
B  0.747004  0.962553  0.139678  0.727101  0.841971  1.709557
C  0.660239  0.883132  0.982043  0.226082  0.561321  1.543371
D  0.601463  0.080718  0.999288  0.407770  0.125858  0.682181
E  0.769375  0.178236  0.528002  0.617595  0.590948  0.947612

In [47]:
test1=pd.read_csv('test2.csv')
print(test1)

  Unnamed: 0         W         X         Y         Z         A    NEWCOL
0          A  0.117022  0.419714  0.341500  0.631714  0.077726  0.536736
1          B  0.747004  0.962553  0.139678  0.727101  0.841971  1.709557
2          C  0.660239  0.883132  0.982043  0.226082  0.561321  1.543371
3          D  0.601463  0.080718  0.999288  0.407770       NaN  0.682181
4          E  0.769375  0.178236  0.528002  0.617595  0.590948  0.947612

In [46]:
test1.isnull()

   Unnamed: 0      W      X      Y      Z      A  NEWCOL
0       False  False  False  False  False  False   False
1       False  False  False  False  False  False   False
2       False  False  False  False  False  False   False
3       False  False  False  False  False  False   False
4       False  False  False  False  False  False   False

In [53]:
titanic = pd.read_csv("titanic.csv")
titanic

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [55]:
titanic.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [56]:
titanic.tail(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [57]:
titanic.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [58]:
titanic.to_excel("titanic.xlsx",sheet_name="pass",index=False)
titanic

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [60]:
titanic=pd.read_excel("titanic.xlsx",sheet_name="pass")
titanic

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [61]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [62]:
ages=titanic['Age']
ages.head()

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
Name: Age, dtype: float64

In [63]:
type(titanic['Age'])

pandas.core.series.Series

In [64]:
titanic["Age"].shapee

(891,)

In [66]:
age_sex=titanic[["Age","Sex"]]
age_sex.head(15)

     Age     Sex
0   22.0    male
1   38.0  female
2   26.0  female
3   35.0  female
4   35.0    male
5    NaN    male
6   54.0    male
7    2.0    male
8   27.0  female
9   14.0  female
10   4.0  female
11  58.0  female
12  20.0    male
13  39.0    male
14  14.0  female

In [67]:
above_35=titanic[titanic["Age"]>35]
above_35

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
865,866,1,2,"Bystrom, Mrs. (Karolina)",female,42.0,0,0,236852,13.0000,NaN,S
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
873,874,0,3,"Vander Cruyssen, Mr. Victor",male,47.0,0,0,345765,9.0000,NaN,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q

In [68]:
titanic["Age"]>35

0      False
1       True
2      False
3      False
4      False
       ...
886    False
887    False
888    False
889    False
890    False
Name: Age, Length: 891, dtype: bool