In [ ]:
#Pandas is a Python library
#Pandas is used to analyze data
#What is Pandas?
#Pandas is a Python library used for working with data sets.
#It has function for analyzing,cleaning,exploring and manipulating data
#To analyze big data and make conclusions based on statistical theories
#Relevant data is very important in datascience
#pip install pandas

In [ ]:
#Pandas Series
#What is a Series?
#A pandas series is like a column in a table
#It is one dimensional array holding data of any type

In [1]:
import pandas as pd
a=[1,7,10]
my1=pd.Series(a)
print(my1)

0     1
1     7
2    10
dtype: int64

In [2]:
print(my1[0])

1

In [3]:
my1=pd.Series(a,index=["x","y","z"])
print(my1)

x     1
y     7
z    10
dtype: int64

In [6]:
print(my1["x"])

1

In [10]:
my2={101:"azar",102:"mohamed",103:"sai"}
result=pd.Series(my2,index=[101,102])
print(result)

101       azar
102    mohamed
dtype: object

In [ ]:
#DataFrames
#Data sets in pandas are usually multi-dimensional tables called dataFrames
#Series is like a column,a dataframe is the whole table

In [11]:
data={"c1":[100,200,300],"c2":[400,500,600]}
my1=pd.DataFrame(data)
print(my1)

    c1   c2
0  100  400
1  200  500
2  300  600

In [ ]:
#Locate Row
#Pandas use the loc attribute to return one or more specified rows

In [14]:
print(my1.loc[0])

c1    100
c2    400
Name: 0, dtype: int64

In [15]:
#Use a list of indexes
print(my1.loc[[0,1]])

    c1   c2
0  100  400
1  200  500

In [ ]:
#Named indexes
#With the index argument you can name your own indexes

In [16]:
my1

    c1   c2
0  100  400
1  200  500
2  300  600

In [20]:
my2=pd.DataFrame(data,index=["d1","d2","d3"])
print(my2)

     c1   c2
d1  100  400
d2  200  500
d3  300  600

In [21]:
#Locate Named Indexes
#Refer to the named index
print(my2.loc["d1"])

c1    100
c2    400
Name: d1, dtype: int64

In [ ]:
#Load files into a dataFrame

In [22]:
df=pd.read_csv('Datasets/Position_Salaries.csv')
df

            Position  Level   Salary
0   Business Analyst      1    45000
1  Junior Consultant      2    50000
2  Senior Consultant      3    60000
3            Manager      4    80000
4    Country Manager      5   110000
5   Regional Manager      6   150000
6            Partner      7   200000
7     Senior Partner      8   300000
8            C-level      9   500000
9                CEO     10  1000000

In [23]:
print(pd.options.display.max_rows)

60

In [24]:
print(pd.options.display.max_columns)

20

In [29]:
data={'One':pd.Series([1,2,3,4],index=['a','b','c','d']),
      'two':pd.Series([1,2,3,4],index=['a','b','c','d'])}
table=pd.DataFrame(data)
table

   One  two
a    1    1
b    2    2
c    3    3
d    4    4